<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerISgEpfx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerISgEpfx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerISgEpfx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerISgEpfx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerISgEpfx\App_KernelDevDebugContainer([
    'container.build_hash' => 'ISgEpfx',
    'container.build_id' => '833207fb',
    'container.build_time' => 1707325367,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerISgEpfx');
