<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container78zm4Lx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container78zm4Lx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container78zm4Lx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container78zm4Lx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container78zm4Lx\App_KernelDevDebugContainer([
    'container.build_hash' => '78zm4Lx',
    'container.build_id' => 'dd623965',
    'container.build_time' => 1707327527,
], __DIR__.\DIRECTORY_SEPARATOR.'Container78zm4Lx');
