<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5toDhys\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5toDhys/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5toDhys.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5toDhys\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5toDhys\App_KernelDevDebugContainer([
    'container.build_hash' => '5toDhys',
    'container.build_id' => '3f229c64',
    'container.build_time' => 1706097144,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5toDhys');
